import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import './common/datatable/dataTables.bootstrap4.min.css';
import './common/css/dashboard.css';
import './common/charts-c3/c3-chart.css';
import './common/morris/morris.css';
import './common/scroll-bar/jquery.mCustomScrollbar.css';
import './common/iconfonts/plugin.css';
import './common/forn-wizard/css/material-bootstrap-wizard.css';
import './common/forn-wizard/css/demo.css';
import 'bootstrap/dist/css/bootstrap.min.css';
ReactDOM.render(<App />, document.getElementById('root'));
